const express = require('express')
const app = express()
require('dotenv').config()
const mongoose = require('mongoose')
const TeacherAuthRoute = require('./Route/teacherAuthRoute')
const StudentAuthRoute = require('./Route/studentAuthRoute')
const teacherRoute = require('./Route/teacherRoute')
const studentRoute=require('./Route/studentRoute')
app.use(express.json())
mongoose.connect(`mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASS}@cluster0.zusrn.mongodb.net/classroom?retryWrites=true&w=majority`)
    .then(res=>{console.log('DB Connected')})
app.use('/api/student/',StudentAuthRoute)
app.use('/api/teacher/', TeacherAuthRoute)
app.use('/api/teacher/', teacherRoute)
app.use('/api/student/',studentRoute)
app.listen(5000, () => { console.log('Server Started...') })