const express = require('express')
const app = express()
require('dotenv').config()
const mongoose = require('mongoose')
const teacherAuthRoute = require('./Route/teacherAuthRoute')
const studentAuthRoute = require('./Route/studentAuthRoute')
const teacherRoute=require('./Route/teacherRoute')
app.use(express.json())
mongoose.connect(`mongodb+srv://${process.env.DB_HOST}:${process.env.DB_PASS}@cluster0.zusrn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`, { useNewUrlParser: true, useUnifiedTopology: true, useCreateIndex: true })
    .then(res => { console.log("Connected to DB") })
app.use('/api/student/',studentAuthRoute)
app.use('/api/teacher/', teacherAuthRoute)
app.use('/api/teacher/',teacherRoute)
app.listen(5000, () => { console.log('Server Started...') })